modLoader="javafml"
loaderVersion="[50,)"
license="CC0-1.0"

[[mods]]
modId="customsplash"
version="${version}"
displayName="Custom Splash"
authors="ArrBrants"
logoFile="assets/customsplash/icon.png"
description='''A mod that replaces or extends the title screen yellow splash text with custom texts, colours, gradients, placeholders and conditions.'''

[[dependencies.customsplash]]
modId="forge"
mandatory=true
versionRange="[50,)"
ordering="NONE"
side="BOTH"

[[dependencies.customsplash]]
modId="minecraft"
mandatory=true
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
