modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"

[[mods]]
modId="customsplash"
version="${version}"
displayName="Custom Splash"
authors="ArrBrants"
logoFile="assets/customsplash/icon.png"
clientSideOnly=true
description='''A mod that replaces or extends the title screen yellow splash text with custom texts, colours, gradients, placeholders and conditions.'''

[[mixins]]
config="customsplash.mixins.json"

[[dependencies.customsplash]]
modId="neoforge"
type="required"
versionRange="[21.0.167,)"
ordering="NONE"
side="BOTH"

[[dependencies.customsplash]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.5)"
ordering="NONE"
side="BOTH"
