buildscript {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.+', changing: true
		classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
	}
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'maven-publish'

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+forge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
base.archivesName = "customsplash-${minecraft_version}-forge"

minecraft {
	mappings channel: 'official', version: minecraft_version
}

mixin {
	add sourceSets.main, 'customsplash.refmap.json'
	config 'customsplash.mixins.json'
}

dependencies {
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
	implementation 'org.spongepowered:mixin:0.8.5'
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_version', minecraft_version
	inputs.property 'forge_version', forge_version
	filesMatching('META-INF/mods.toml') {
		expand version: project.version, minecraft_version: minecraft_version, forge_version: forge_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = Integer.parseInt(java_version)
}

jar {
	finalizedBy 'reobfJar'
	manifest {
		attributes 'MixinConfigs': 'customsplash.mixins.json'
	}
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
