#!/usr/bin/env python3
"""Generate the NeoForge version projects (1.20.5 - 26.3).

For every Minecraft version in supported-neoforge-versions.txt this script
writes a complete standalone ModDevGradle project under
versions/<mc>-neoforge. It reuses the exact same shared sources and mixins
generated by scripts/generate_common_sources.py (imported here), plus the two
NeoForge-only classes: the @Mod entry point and the SplashPlatform
implementation.

Build recipes mirror the official MDK-<mc>-ModDevGradle templates:
  - ModDevGradle 2.0.148 on Gradle 9.2.1
  - NeoForge versions pinned from the same MDKs
  - mixin config declared through the [[mixins]] block in neoforge.mods.toml;
    NeoForge runs on official names, so no refmap is needed
  - the neoforge.mods.toml templates with modLoader/loaderVersion only exist
    up to 1.21.4; newer versions drop both lines

1.20.5 is the exception: ModDevGradle 2.x needs the neoforge-moddev-bundle
variant that NeoForge 20.5 metadata predates, so that project uses the legacy
NeoGradle userdev plugin (7.1.39) instead, matching its official NeoGradle MDK.

Run from the repository root: python3 scripts/generate_neoforge_projects.py
"""

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from generate_common_sources import (SOURCES, fabric_project_for, mixin_for,  # noqa: E402
                                    read_supported_versions, write_icon)

PACKAGE_DIR = Path("src/main/java/dev/arrbrants/customsplash")
RESOURCES_DIR = Path("src/main/resources")
NEOFORGE_VERSIONS_FILE = ROOT / "supported-neoforge-versions.txt"

# minecraft -> (neoforge_version, java_version, classic_metadata)
# classic_metadata: neoforge.mods.toml keeps modLoader/loaderVersion up to
# 1.21.4; from 1.21.5 the format dropped those lines.
NEOFORGE_SPECS = {
    "1.20.5": ("20.5.21-beta", "21", True),
    "1.21": ("21.0.167", "21", True),
    "1.21.1": ("21.1.252", "21", True),
    "1.21.2": ("21.2.1-beta", "21", True),
    "1.21.3": ("21.3.97", "21", True),
    "1.21.4": ("21.4.158", "21", True),
    "1.21.5": ("21.5.98", "21", False),
    "1.21.6": ("21.6.20-beta", "21", False),
    "1.21.7": ("21.7.25-beta", "21", False),
    "1.21.8": ("21.8.54", "21", False),
    "1.21.9": ("21.9.16-beta", "21", False),
    "1.21.10": ("21.10.64", "21", False),
    "1.21.11": ("21.11.45", "21", False),
    "26.1": ("26.1.0.19-beta", "25", False),
    "26.1.1": ("26.1.1.15-beta", "25", False),
    "26.1.2": ("26.1.2.112", "25", False),
    "26.2": ("26.2.0.88", "25", False),
    "26.3": ("26.3.0.23-beta", "25", False),
}

MODDED_GRADLE = "9.6.0"


def uses_neogradle(minecraft: str) -> bool:
    """NeoForge 20.5 predates the metadata ModDevGradle 2.x requires."""
    return minecraft == "1.20.5"


def gradle_distribution_url(minecraft: str) -> str:
    return "https\\://services.gradle.org/distributions/gradle-%s-bin.zip" % MODDED_GRADLE


def mixin_compatibility(minecraft: str) -> str:
    return "JAVA_%s" % NEOFORGE_SPECS[minecraft][1]


def write(project: Path, relative: Path, content: str) -> None:
    target = project / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def copy_wrapper(project: Path, minecraft: str) -> None:
    """Reuse the wrapper scripts and jar from the Fabric project covering it."""
    source = ROOT / "versions" / fabric_project_for(minecraft)
    (project / "gradle" / "wrapper").mkdir(parents=True, exist_ok=True)
    for name in ("gradlew", "gradlew.bat", "gradle/wrapper/gradle-wrapper.jar"):
        shutil.copyfile(source / name, project / name)
    (project / "gradlew").chmod(0o755)
    write(project, Path("gradle/wrapper/gradle-wrapper.properties"),
          WRAPPER_PROPERTIES.replace("%%DIST_URL%%", gradle_distribution_url(minecraft)))


BUILD_GRADLE = r"""plugins {
	id 'java-library'
	id 'net.neoforged.moddev' version '2.0.148'
}

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+neoforge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
base.archivesName = "custom-splash-${minecraft_version}-neoforge"

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

neoForge {
	version = project.neo_version
	mods {
		"custom-splash" {
			sourceSet(sourceSets.main)
		}
	}
}

dependencies {
	compileOnly 'org.spongepowered:mixin:0.8.5'
}

processResources {
	inputs.property 'version', project.version
	filesMatching('META-INF/neoforge.mods.toml') {
		expand version: project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

// NeoForge runs on official names, so no reobfuscation or refmap is needed;
// the mixin config is declared in neoforge.mods.toml.
jar {
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
"""

SETTINGS_GRADLE = r"""pluginManagement {
	repositories {
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'custom-splash-%%MINECRAFT%%-neoforge'
"""

# NeoForge 20.5 metadata predates the neoforge-moddev-bundle variant that
# ModDevGradle 2.x requires, so that project uses the legacy NeoGradle tooling
# exactly like its official MDK-1.20.5-NeoGradle template.
BUILD_GRADLE_NEOGRADLE = r"""plugins {
	id 'java-library'
	id 'net.neoforged.gradle.userdev' version '7.1.39'
}

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+neoforge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
base.archivesName = "custom-splash-${minecraft_version}-neoforge"

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

dependencies {
	implementation "net.neoforged:neoforge:${neo_version}"
	compileOnly 'org.spongepowered:mixin:0.8.5'
}

processResources {
	inputs.property 'version', project.version
	filesMatching('META-INF/neoforge.mods.toml') {
		expand version: project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

// NeoForge runs on official names, so no reobfuscation or refmap is needed;
// the mixin config is declared in neoforge.mods.toml.
jar {
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
"""

SETTINGS_GRADLE_NEOGRADLE = r"""pluginManagement {
	repositories {
		gradlePluginPortal()
		maven { url = 'https://maven.neoforged.net/releases' }
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'custom-splash-%%MINECRAFT%%-neoforge'
"""

GRADLE_PROPERTIES = """minecraft_version=%%MINECRAFT%%
neo_version=%%NEO%%
java_version=%%JAVA%%
mod_version=1.2.0
maven_group=dev.arrbrants.customsplash
org.gradle.java.installations.fromEnv=JAVA_HOME_21_X64,JAVA_HOME_25_X64
"""

WRAPPER_PROPERTIES = """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=%%DIST_URL%%
networkTimeout=10000
retries=0
retryBackOffMs=500
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""

NEOFORGE_MODS_TOML = r"""modLoader="javafml"
loaderVersion="[1,)"
license="CC0-1.0"

[[mods]]
modId="custom-splash"
version="${version}"
displayName="Custom Splash"
authors="ArrBrants"
logoFile="assets/custom-splash/icon.png"
clientSideOnly=true
description='''A mod that replaces or extends the title screen yellow splash text with custom texts, colours, gradients, placeholders and conditions.'''

[[mixins]]
config="customsplash.mixins.json"

[[dependencies.custom-splash]]
modId="neoforge"
type="required"
versionRange="[%%NEO%%,)"
ordering="NONE"
side="BOTH"

[[dependencies.custom-splash]]
modId="minecraft"
type="required"
versionRange="[%%MC%%]"
ordering="NONE"
side="BOTH"
"""

# From 1.21.5 on the metadata format dropped modLoader and loaderVersion.
NEOFORGE_MODS_TOML_MODERN = r"""license="CC0-1.0"

[[mods]]
modId="custom-splash"
version="${version}"
displayName="Custom Splash"
authors="ArrBrants"
logoFile="assets/custom-splash/icon.png"
clientSideOnly=true
description='''A mod that replaces or extends the title screen yellow splash text with custom texts, colours, gradients, placeholders and conditions.'''

[[mixins]]
config="customsplash.mixins.json"

[[dependencies.custom-splash]]
modId="neoforge"
type="required"
versionRange="[%%NEO%%,)"
ordering="NONE"
side="BOTH"

[[dependencies.custom-splash]]
modId="minecraft"
type="required"
versionRange="[%%MC%%]"
ordering="NONE"
side="BOTH"
"""

MIXINS_JSON = r"""{
	"required": true,
	"package": "dev.arrbrants.customsplash.mixin",
	"compatibilityLevel": "%%COMPAT%%",
	"minVersion": "0.8",
	"client": ["SplashManagerMixin"],
	"injectors": {"defaultRequire": 1}
}
"""

NEOFORGE_PLATFORM = r"""package dev.arrbrants.customsplash;

import net.neoforged.fml.ModList;
import net.neoforged.fml.loading.FMLPaths;

import java.nio.file.Path;

/**
 * NeoForge implementation of {@link SplashPlatform}, installed by
 * {@link CustomSplash} at mod construction time.
 */
public final class NeoForgeSplashPlatform implements SplashPlatform {

	private NeoForgeSplashPlatform() {
	}

	public static void install() {
		SplashPlatform.install(new NeoForgeSplashPlatform());
	}

	@Override
	public Path getConfigDir() {
		return FMLPaths.CONFIGDIR.get();
	}

	@Override
	public Path getGameDir() {
		return FMLPaths.GAMEDIR.get();
	}

	@Override
	public boolean isModLoaded(String modId) {
		return ModList.get().isLoaded(modId);
	}

	@Override
	public int loadedModCount() {
		return ModList.get().getMods().size();
	}
}
"""

NEOFORGE_INITIALIZER = r"""package dev.arrbrants.customsplash;

import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Mod(CustomSplash.MOD_ID)
public class CustomSplash {
	public static final String MOD_ID = "custom-splash";
	public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

	public CustomSplash(IEventBus modEventBus) {
		NeoForgeSplashPlatform.install();
		modEventBus.addListener(this::onCommonSetup);
		LOGGER.info("Custom Splash has initialized");
	}

	private void onCommonSetup(FMLCommonSetupEvent event) {
		SplashRegistry.reload();
	}
}
"""


def main() -> None:
	versions = NEOFORGE_VERSIONS_FILE.read_text().splitlines()
	fabric_versions = read_supported_versions()
	for minecraft in versions:
		if minecraft not in NEOFORGE_SPECS:
			raise SystemExit(f"no NeoForge spec for {minecraft}")
		if minecraft not in fabric_versions:
			raise SystemExit(f"{minecraft} is not a Fabric version project")

		neo_version, java_version, classic = NEOFORGE_SPECS[minecraft]
		project = ROOT / "versions" / f"{minecraft}-neoforge"
		if uses_neogradle(minecraft):
			build_gradle = BUILD_GRADLE_NEOGRADLE
			settings_gradle = SETTINGS_GRADLE_NEOGRADLE
		else:
			build_gradle = BUILD_GRADLE
			settings_gradle = SETTINGS_GRADLE
		write(project, Path("build.gradle"), build_gradle)
		write(project, Path("settings.gradle"),
		      settings_gradle.replace("%%MINECRAFT%%", minecraft))
		write(project, Path("gradle.properties"),
		      GRADLE_PROPERTIES
		      .replace("%%MINECRAFT%%", minecraft)
		      .replace("%%NEO%%", neo_version)
		      .replace("%%JAVA%%", java_version))
		copy_wrapper(project, minecraft)

		for name, content in SOURCES.items():
			write(project, PACKAGE_DIR / name, content)
		write(project, PACKAGE_DIR / "NeoForgeSplashPlatform.java", NEOFORGE_PLATFORM)
		write(project, PACKAGE_DIR / "CustomSplash.java", NEOFORGE_INITIALIZER)
		write(project, PACKAGE_DIR / "mixin" / "SplashManagerMixin.java", mixin_for(minecraft))

		template = NEOFORGE_MODS_TOML if classic else NEOFORGE_MODS_TOML_MODERN
		write(project, RESOURCES_DIR / "META-INF" / "neoforge.mods.toml",
		      template
		      .replace("%%NEO%%", neo_version)
		      .replace("%%MC%%", minecraft))
		write(project, RESOURCES_DIR / "customsplash.mixins.json",
		      MIXINS_JSON.replace("%%COMPAT%%", mixin_compatibility(minecraft)))
		write_icon(project)
		print(f"updated neoforge {minecraft}")


if __name__ == "__main__":
	main()
