#!/usr/bin/env python3
"""Generate the Forge version projects (1.16.1 - 1.20.6).

For every Minecraft version in supported-forge-versions.txt this script writes
a complete standalone ForgeGradle project under versions/<mc>-forge. It reuses
the exact same shared sources and mixins generated by
scripts/generate_common_sources.py (imported here), plus the two Forge-only
classes: the @Mod entry point and the SplashPlatform implementation. The 1.16.x
mixins are retargeted to the SRG class name because those MCPConfigs predate
official class mappings (see forge_mixin_for).

Build recipes mirror the official Forge MDK templates:
  - 1.16.1..1.19.4: ForgeGradle 5.1.+ on Gradle 7.6.4
  - 1.20.1..1.20.4: ForgeGradle 6.+ on Gradle 8.13
  - 1.20.6:         ForgeGradle 7.x on Gradle 9.6.0 (official runtime names,
                    no reobfuscation and no mixin refmap)
The ForgeGradle 5/6 projects apply MixinGradle 0.7-SNAPSHOT via the buildscript
classpath, declare the refmap and mixin config in the mixin closure and
finalize the jar with reobfJar, exactly like the MDK's mixin workflow.

Run from the repository root: python3 scripts/generate_forge_projects.py
"""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from generate_common_sources import (FORGE_TARGETS_FILE, check_range,  # noqa: E402
                                    copy_wrapper, mixin_for, read_supported_versions,
                                    read_targets, write, write_shared_sources)

PACKAGE_DIR = Path("src/main/java/dev/arrbrants/customsplash")
RESOURCES_DIR = Path("src/main/resources")
FORGE_VERSIONS_FILE = ROOT / "supported-forge-versions.txt"

# Forge exposes a mod's resources as a resource pack and refuses to finish loading
# without pack metadata: 1.20.4 stops with "Missing metadata in pack mod:<id>" and
# older Forge logs "Couldn't get pack info for ... 'pack.mcmeta'". Fabric does not
# need one, which is why the jars shipped without it. The value is the resource
# pack format of the release each line is compiled against.
PACK_FORMAT = {
    "1.16.1": 5,
    "1.17.1": 7,
    "1.20": 15,
    "1.20.6": 32,
}

PACK_MCMETA = """{
\t"pack": {
\t\t"description": "Custom Splash resources",
\t\t"pack_format": %%FORMAT%%
\t}
}
"""

# minecraft -> (forge_version, java_version, fml_loader_range, minecraft_range)
FORGE_SPECS = {
    "1.16.1": ("32.0.108", "8", "[32,)", "[1.16.1,1.16.2)"),
    "1.16.2": ("33.0.61", "8", "[33,)", "[1.16.2,1.16.3)"),
    "1.16.3": ("34.1.42", "8", "[34,)", "[1.16.3,1.16.4)"),
    "1.16.4": ("35.1.37", "8", "[35,)", "[1.16.4,1.16.5)"),
    "1.16.5": ("36.2.42", "8", "[36,)", "[1.16.5,1.17)"),
    "1.17.1": ("37.1.1", "16", "[37,)", "[1.17.1,1.18)"),
    "1.18": ("38.0.17", "17", "[38,)", "[1.18,1.18.1)"),
    "1.18.1": ("39.1.2", "17", "[39,)", "[1.18.1,1.19)"),
    "1.18.2": ("40.3.12", "17", "[40,)", "[1.18.2,1.19)"),
    "1.19": ("41.1.0", "17", "[41,)", "[1.19,1.20)"),
    "1.19.1": ("42.0.2", "17", "[42,)", "[1.19.1,1.20)"),
    "1.19.2": ("43.5.2", "17", "[43,)", "[1.19.2,1.20)"),
    "1.19.3": ("44.1.23", "17", "[44,)", "[1.19.3,1.20)"),
    "1.19.4": ("45.4.3", "17", "[45,)", "[1.19.4,1.20)"),
    "1.20": ("46.0.14", "17", "[46,)", "[1.20,1.20.1)"),
    "1.20.1": ("47.4.26", "17", "[47,)", "[1.20.1,1.21)"),
    "1.20.2": ("48.1.0", "17", "[48,)", "[1.20.2,1.21)"),
    "1.20.3": ("49.0.2", "17", "[49,)", "[1.20.3,1.21)"),
    "1.20.4": ("49.2.8", "17", "[49,)", "[1.20.4,1.21)"),
    "1.20.6": ("50.2.10", "21", "[50,)", "[1.20.6,1.21)"),
}


def is_fg7(minecraft: str) -> bool:
    """1.20.5+ switched to official runtime names and ForgeGradle 7."""
    major, minor, *patch = (int(p) for p in minecraft.split("."))
    if (major, minor) != (1, 20):
        return (major, minor) > (1, 20)
    return bool(patch) and patch[0] >= 5


def is_fg6(minecraft: str) -> bool:
    major, minor = (int(p) for p in minecraft.split(".")[:2])
    return (major, minor) >= (1, 20)


def mixin_compatibility(minecraft: str) -> str:
    # Forge 1.20.6 bundles Mixin 0.8.5, whose CompatibilityLevel enum stops at
    # JAVA_17, so naming a newer level aborts startup with a MixinInitialisationError.
    # NeoForge ships a newer Mixin and is free to name JAVA_21 and up.
    if minecraft.startswith("1.16"):
        return "JAVA_8"
    if minecraft == "1.17.1":
        return "JAVA_16"
    return "JAVA_17"


def gradle_distribution_url(minecraft: str) -> str:
    if is_fg7(minecraft):
        version = "9.6.0"
    elif is_fg6(minecraft):
        version = "8.13"
    else:
        version = "7.6.4"
    return "https\\://services.gradle.org/distributions/gradle-%s-bin.zip" % version


def forge_mixin_for(minecraft: str) -> str:
    """The shared mixin, adjusted for Forge's mapping behaviour.

    The 1.16.x MCPConfigs are the only supported ones not marked official:
    ForgeGradle keeps the SRG class names there (only fields and methods are
    renamed to the Mojang names), so those mixins have to target
    ``net.minecraft.client.util.Splashes`` instead of the official
    ``net.minecraft.client.resources.SplashManager``.
    """
    source = mixin_for(minecraft)
    if minecraft.startswith("1.16"):
        source = source.replace(
            "import net.minecraft.client.resources.SplashManager;",
            "import net.minecraft.client.util.Splashes;",
        ).replace(
            "@Mixin(SplashManager.class)",
            "@Mixin(Splashes.class)",
        )
    return source


BUILD_GRADLE_FG5 = r"""buildscript {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
		classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
	}
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'maven-publish'

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+forge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
archivesBaseName = "customsplash-${minecraft_version}-forge"

minecraft {
	mappings channel: 'official', version: minecraft_version
}

mixin {
	add sourceSets.main, 'customsplash.refmap.json'
	config 'customsplash.mixins.json'
}

dependencies {
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
	implementation 'org.spongepowered:mixin:0.8.5'
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_version', minecraft_version
	inputs.property 'forge_version', forge_version
	filesMatching('META-INF/mods.toml') {
		expand version: project.version, minecraft_version: minecraft_version, forge_version: forge_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	// ForgeGradle compiles with the JDK matching the Minecraft version (Java 8
	// for 1.16.5), and javac 8 does not support the --release flag.
	sourceCompatibility = java_version
	targetCompatibility = java_version
}

jar {
	finalizedBy 'reobfJar'
	manifest {
		attributes 'MixinConfigs': 'customsplash.mixins.json'
	}
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${archivesBaseName}" }
	}
}
"""

BUILD_GRADLE_FG6 = r"""buildscript {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.+', changing: true
		classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
	}
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'maven-publish'

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+forge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
base.archivesName = "customsplash-${minecraft_version}-forge"

minecraft {
	mappings channel: 'official', version: minecraft_version
}

mixin {
	add sourceSets.main, 'customsplash.refmap.json'
	config 'customsplash.mixins.json'
}

dependencies {
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
	implementation 'org.spongepowered:mixin:0.8.5'
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_version', minecraft_version
	inputs.property 'forge_version', forge_version
	filesMatching('META-INF/mods.toml') {
		expand version: project.version, minecraft_version: minecraft_version, forge_version: forge_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = Integer.parseInt(java_version)
}

jar {
	finalizedBy 'reobfJar'
	manifest {
		attributes 'MixinConfigs': 'customsplash.mixins.json'
	}
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
"""

BUILD_GRADLE_FG7 = r"""plugins {
	id 'java'
	id 'maven-publish'
	id 'net.minecraftforge.gradle' version '[7.0.29,8.0)'
}

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+forge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
base.archivesName = "customsplash-${minecraft_version}-forge"

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

minecraft {
	mappings channel: 'official', version: minecraft_version
}

repositories {
	minecraft.mavenizer(it)
	maven fg.forgeMaven
	maven fg.minecraftLibsMaven
	mavenCentral()
}

dependencies {
	implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
	compileOnly 'org.spongepowered:mixin:0.8.5'
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_version', minecraft_version
	inputs.property 'forge_version', forge_version
	filesMatching('META-INF/mods.toml') {
		expand version: project.version, minecraft_version: minecraft_version, forge_version: forge_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

// 1.20.5+ runs on official names, so ForgeGradle 7 needs no reobfuscation and
// the mixin needs no refmap; the config is announced via the manifest.
jar {
	manifest {
		attributes 'MixinConfigs': 'customsplash.mixins.json'
	}
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
"""

# ForgeGradle 5 runs on Gradle 7, whose settings script has no toolchain API and
# cannot resolve the foojay resolver convention plugin (it requires Gradle 8.2+).
SETTINGS_GRADLE_FG5 = r"""pluginManagement {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'customsplash-%%MINECRAFT%%-forge'
"""

SETTINGS_GRADLE_FG6 = r"""pluginManagement {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'customsplash-%%MINECRAFT%%-forge'
"""

# ForgeGradle 7 is published on the Gradle Plugin Portal, so the settings
# script needs no pluginManagement block.
SETTINGS_GRADLE_FG7 = r"""plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'customsplash-%%MINECRAFT%%-forge'
"""

GRADLE_PROPERTIES = """minecraft_version=%%MINECRAFT%%
forge_version=%%FORGE%%
java_version=%%JAVA%%
mod_version=1.2.0
maven_group=dev.arrbrants.customsplash
org.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_16_X64,JAVA_HOME_17_X64
"""

GRADLE_PROPERTIES_FG7 = """minecraft_version=%%MINECRAFT%%
forge_version=%%FORGE%%
java_version=%%JAVA%%
mod_version=1.2.0
maven_group=dev.arrbrants.customsplash
org.gradle.java.installations.fromEnv=JAVA_HOME_21_X64
"""

WRAPPER_PROPERTIES = """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=%%DIST_URL%%
networkTimeout=10000
retries=0
retryBackOffMs=500
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""

MODS_TOML = r"""modLoader="javafml"
loaderVersion="%%LOADER_RANGE%%"
license="CC0-1.0"

[[mods]]
modId="customsplash"
version="${version}"
displayName="Custom Splash"
authors="ArrBrants"
logoFile="assets/customsplash/icon.png"
description='''A mod that replaces or extends the title screen yellow splash text with custom texts, colours, gradients, placeholders and conditions.'''

[[dependencies.customsplash]]
modId="forge"
mandatory=true
versionRange="%%LOADER_RANGE%%"
ordering="NONE"
side="BOTH"

[[dependencies.customsplash]]
modId="minecraft"
mandatory=true
versionRange="%%MC_RANGE%%"
ordering="NONE"
side="BOTH"
"""

MIXINS_JSON = r"""{
	"required": true,
	"package": "dev.arrbrants.customsplash.mixin",
	"compatibilityLevel": "%%COMPAT%%",
	"refmap": "customsplash.refmap.json",
	"minVersion": "0.8",
	"client": ["SplashManagerMixin"],
	"injectors": {"defaultRequire": 1}
}
"""

# 1.20.5+ runs on official names, so no refmap is generated or needed.
MIXINS_JSON_NOREFMAP = r"""{
	"required": true,
	"package": "dev.arrbrants.customsplash.mixin",
	"compatibilityLevel": "%%COMPAT%%",
	"minVersion": "0.8",
	"client": ["SplashManagerMixin"],
	"injectors": {"defaultRequire": 1}
}
"""

FORGE_PLATFORM = r"""package dev.arrbrants.customsplash;

import net.minecraftforge.fml.ModList;
import net.minecraftforge.fml.loading.FMLPaths;

import java.nio.file.Path;

/**
 * Forge implementation of {@link SplashPlatform}, installed by
 * {@link CustomSplash} at mod construction time.
 */
public final class ForgeSplashPlatform implements SplashPlatform {

	private ForgeSplashPlatform() {
	}

	public static void install() {
		SplashPlatform.install(new ForgeSplashPlatform());
	}

	@Override
	public Path getConfigDir() {
		return FMLPaths.CONFIGDIR.get();
	}

	@Override
	public Path getGameDir() {
		return FMLPaths.GAMEDIR.get();
	}

	@Override
	public boolean isModLoaded(String modId) {
		return ModList.get().isLoaded(modId);
	}

	@Override
	public int loadedModCount() {
		return ModList.get().getMods().size();
	}
}
"""

FORGE_INITIALIZER = r"""package dev.arrbrants.customsplash;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod(CustomSplash.MOD_ID)
public class CustomSplash {
	public static final String MOD_ID = "customsplash";
	public static final Logger LOGGER = LogManager.getLogger(MOD_ID);

	public CustomSplash() {
		ForgeSplashPlatform.install();
		FMLJavaModLoadingContext.get().getModEventBus().addListener(this::onCommonSetup);
		LOGGER.info("Custom Splash has initialized");
	}

	private void onCommonSetup(FMLCommonSetupEvent event) {
		SplashRegistry.reload();
	}
}
"""


def key(version: str) -> tuple:
	return tuple(int(part) for part in version.split("."))


def forge_group_ranges(covered: list, next_first) -> tuple:
	"""The loader and Minecraft ranges that cover a whole Forge line.

	The oldest release supplies the loader range, which then spans every Forge
	version in the line. The upper bound is the next line's first release whenever
	that comes sooner than the spec's own end, so a line never claims a release
	belonging to a later one: the 1.20-1.20.4 jar resolves getSplash through a
	refmap while Forge uses official names from 1.20.6, so a range reaching 1.21
	offered that jar where its mixin cannot apply.
	"""
	loader_range = FORGE_SPECS[covered[0]][2]
	match = re.fullmatch(r"\[[^,]+,([^)]+)\)", FORGE_SPECS[covered[-1]][3])
	if not match:
		raise SystemExit(f"unexpected Minecraft range: {FORGE_SPECS[covered[-1]][3]}")
	upper = match.group(1)
	if next_first is not None and key(next_first) < key(upper):
		upper = next_first
	return loader_range, f"[{covered[0]},{upper})"


def main() -> None:
	fabric_versions = read_supported_versions()
	targets = read_targets(FORGE_TARGETS_FILE)
	listed = [version for _target, _compile, covered in targets for version in covered]
	if listed != FORGE_VERSIONS_FILE.read_text().split():
		raise SystemExit("forge-targets.txt must cover supported-forge-versions.txt exactly, in order")
	for index, (target, compile_version, covered) in enumerate(targets):
		if not target.endswith("-forge"):
			raise SystemExit(f"a Forge target must be named <mc>-forge, got {target}")
		for minecraft in covered:
			if minecraft not in FORGE_SPECS:
				raise SystemExit(f"no Forge spec for {minecraft}")
			if minecraft not in fabric_versions:
				raise SystemExit(f"{minecraft} is not a Fabric version project")
		if compile_version not in PACK_FORMAT:
			raise SystemExit(f"no resource pack format for {compile_version}")

		forge_version, java_version = FORGE_SPECS[compile_version][:2]
		next_first = targets[index + 1][2][0] if index + 1 < len(targets) else None
		loader_range, mc_range = forge_group_ranges(covered, next_first)
		check_range(covered, mc_range.rsplit(",", 1)[1][:-1], FORGE_TARGETS_FILE)
		project = ROOT / "versions" / target
		if is_fg7(compile_version):
			build_gradle = BUILD_GRADLE_FG7
			settings_gradle = SETTINGS_GRADLE_FG7
			properties = GRADLE_PROPERTIES_FG7
			mixins_json = MIXINS_JSON_NOREFMAP
		elif is_fg6(compile_version):
			build_gradle = BUILD_GRADLE_FG6
			settings_gradle = SETTINGS_GRADLE_FG6
			properties = GRADLE_PROPERTIES
			mixins_json = MIXINS_JSON
		else:
			build_gradle = BUILD_GRADLE_FG5
			settings_gradle = SETTINGS_GRADLE_FG5
			properties = GRADLE_PROPERTIES
			mixins_json = MIXINS_JSON
		write(project, Path("build.gradle"), build_gradle)
		write(project, Path("settings.gradle"),
		      settings_gradle.replace("%%MINECRAFT%%", compile_version))
		write(project, Path("gradle.properties"),
		      properties
		      .replace("%%MINECRAFT%%", compile_version)
		      .replace("%%FORGE%%", forge_version)
		      .replace("%%JAVA%%", java_version))
		copy_wrapper(project, compile_version, WRAPPER_PROPERTIES,
		             gradle_distribution_url(compile_version))

		write_shared_sources(project, "ForgeSplashPlatform.java", FORGE_PLATFORM,
		                     FORGE_INITIALIZER, forge_mixin_for(compile_version))

		write(project, RESOURCES_DIR / "META-INF" / "mods.toml",
		      MODS_TOML
		      .replace("%%LOADER_RANGE%%", loader_range)
		      .replace("%%MC_RANGE%%", mc_range))
		write(project, RESOURCES_DIR / "customsplash.mixins.json",
		      mixins_json.replace("%%COMPAT%%", mixin_compatibility(compile_version)))
		write(project, RESOURCES_DIR / "pack.mcmeta",
		      PACK_MCMETA.replace("%%FORMAT%%", str(PACK_FORMAT[compile_version])))
		print(f"updated forge {target}")


if __name__ == "__main__":
	main()
