#!/usr/bin/env python3
"""Generate the Forge version projects (1.16.5 - 1.20.4).

For every Minecraft version in supported-forge-versions.txt this script writes
a complete standalone ForgeGradle project under versions/<mc>-forge. It reuses
the exact same shared sources and mixins generated by
scripts/generate_common_sources.py (imported here), plus the two Forge-only
classes: the @Mod entry point and the SplashPlatform implementation.

Build recipes mirror the official Forge MDK templates:
  - 1.16.5..1.19.4: ForgeGradle 5.1.+ on Gradle 7.6.4
  - 1.20.1..1.20.4: ForgeGradle 6.+ on Gradle 8.13
Both apply MixinGradle 0.7-SNAPSHOT via the buildscript classpath, declare the
refmap and mixin config in the mixin closure and finalize the jar with
reobfJar, exactly like the MDK's mixin workflow.

Run from the repository root: python3 scripts/generate_forge_projects.py
"""

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from generate_common_sources import SOURCES, mixin_for  # noqa: E402

PACKAGE_DIR = Path("src/main/java/dev/arrbrants/customsplash")
RESOURCES_DIR = Path("src/main/resources")
FORGE_VERSIONS_FILE = ROOT / "supported-forge-versions.txt"

# minecraft -> (forge_version, java_version, fml_loader_range, minecraft_range)
FORGE_SPECS = {
    "1.16.5": ("36.2.42", "8", "[36,)", "[1.16.5,1.17)"),
    "1.17.1": ("37.1.1", "16", "[37,)", "[1.17.1,1.18)"),
    "1.18.1": ("39.1.2", "17", "[39,)", "[1.18.1,1.19)"),
    "1.18.2": ("40.3.12", "17", "[40,)", "[1.18.2,1.19)"),
    "1.19": ("41.1.0", "17", "[41,)", "[1.19,1.20)"),
    "1.19.1": ("42.0.2", "17", "[42,)", "[1.19.1,1.20)"),
    "1.19.2": ("43.5.2", "17", "[43,)", "[1.19.2,1.20)"),
    "1.19.3": ("44.1.23", "17", "[44,)", "[1.19.3,1.20)"),
    "1.19.4": ("45.4.3", "17", "[45,)", "[1.19.4,1.20)"),
    "1.20.1": ("47.4.26", "17", "[47,)", "[1.20.1,1.21)"),
    "1.20.2": ("48.1.0", "17", "[48,)", "[1.20.2,1.21)"),
    "1.20.3": ("49.0.2", "17", "[49,)", "[1.20.3,1.21)"),
    "1.20.4": ("49.2.8", "17", "[49,)", "[1.20.4,1.21)"),
}


def is_fg6(minecraft: str) -> bool:
    major, minor = (int(p) for p in minecraft.split(".")[:2])
    return (major, minor) >= (1, 20)


def mixin_compatibility(minecraft: str) -> str:
    if minecraft == "1.16.5":
        return "JAVA_8"
    if minecraft == "1.17.1":
        return "JAVA_16"
    return "JAVA_17"


def gradle_distribution_url(minecraft: str) -> str:
    version = "8.13" if is_fg6(minecraft) else "7.6.4"
    return "https\\://services.gradle.org/distributions/gradle-%s-bin.zip" % version


def write(project: Path, relative: Path, content: str) -> None:
    target = project / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def copy_wrapper(project: Path, minecraft: str) -> None:
    """Reuse the wrapper scripts and jar from the matching Fabric project."""
    source = ROOT / "versions" / minecraft
    (project / "gradle" / "wrapper").mkdir(parents=True, exist_ok=True)
    for name in ("gradlew", "gradlew.bat", "gradle/wrapper/gradle-wrapper.jar"):
        shutil.copyfile(source / name, project / name)
    (project / "gradlew").chmod(0o755)
    write(project, Path("gradle/wrapper/gradle-wrapper.properties"),
          WRAPPER_PROPERTIES.replace("%%DIST_URL%%", gradle_distribution_url(minecraft)))


BUILD_GRADLE_FG5 = r"""buildscript {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
		classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
	}
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'maven-publish'

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+forge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
archivesBaseName = "custom-splash-${minecraft_version}-forge"

minecraft {
	mappings channel: 'official', version: minecraft_version
}

mixin {
	add sourceSets.main, 'customsplash.refmap.json'
	config 'customsplash.mixins.json'
}

dependencies {
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
	implementation 'org.spongepowered:mixin:0.8.5'
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_version', minecraft_version
	inputs.property 'forge_version', forge_version
	filesMatching('META-INF/mods.toml') {
		expand version: project.version, minecraft_version: minecraft_version, forge_version: forge_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = Integer.parseInt(java_version)
}

jar {
	finalizedBy 'reobfJar'
	manifest {
		attributes 'MixinConfigs': 'customsplash.mixins.json'
	}
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${archivesBaseName}" }
	}
}
"""

BUILD_GRADLE_FG6 = r"""buildscript {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.+', changing: true
		classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
	}
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'maven-publish'

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+forge-mc${minecraft_version}" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
base.archivesName = "custom-splash-${minecraft_version}-forge"

minecraft {
	mappings channel: 'official', version: minecraft_version
}

mixin {
	add sourceSets.main, 'customsplash.refmap.json'
	config 'customsplash.mixins.json'
}

dependencies {
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
	implementation 'org.spongepowered:mixin:0.8.5'
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_version', minecraft_version
	inputs.property 'forge_version', forge_version
	filesMatching('META-INF/mods.toml') {
		expand version: project.version, minecraft_version: minecraft_version, forge_version: forge_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = Integer.parseInt(java_version)
}

jar {
	finalizedBy 'reobfJar'
	manifest {
		attributes 'MixinConfigs': 'customsplash.mixins.json'
	}
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
"""

# ForgeGradle 5 runs on Gradle 7, whose settings script has no toolchain API and
# cannot resolve the foojay resolver convention plugin (it requires Gradle 8.2+).
SETTINGS_GRADLE_FG5 = r"""pluginManagement {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'custom-splash-%%MINECRAFT%%-forge'
"""

SETTINGS_GRADLE_FG6 = r"""pluginManagement {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'custom-splash-%%MINECRAFT%%-forge'
"""

GRADLE_PROPERTIES = """minecraft_version=%%MINECRAFT%%
forge_version=%%FORGE%%
java_version=%%JAVA%%
mod_version=1.2.0
maven_group=dev.arrbrants.customsplash
"""

WRAPPER_PROPERTIES = """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=%%DIST_URL%%
networkTimeout=10000
retries=0
retryBackOffMs=500
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""

MODS_TOML = r"""modLoader="javafml"
loaderVersion="%%LOADER_RANGE%%"
license="CC0-1.0"

[[mods]]
modId="custom-splash"
version="${version}"
displayName="Custom Splash"
authors="ArrBrants"
description='''A mod that replaces or extends the title screen yellow splash text with custom texts, colours, gradients, placeholders and conditions.'''

[[dependencies.custom-splash]]
modId="forge"
mandatory=true
versionRange="%%LOADER_RANGE%%"
ordering="NONE"
side="BOTH"

[[dependencies.custom-splash]]
modId="minecraft"
mandatory=true
versionRange="%%MC_RANGE%%"
ordering="NONE"
side="BOTH"
"""

MIXINS_JSON = r"""{
	"required": true,
	"package": "dev.arrbrants.customsplash.mixin",
	"compatibilityLevel": "%%COMPAT%%",
	"refmap": "customsplash.refmap.json",
	"minVersion": "0.8",
	"client": ["SplashManagerMixin"],
	"injectors": {"defaultRequire": 1}
}
"""

FORGE_PLATFORM = r"""package dev.arrbrants.customsplash;

import net.minecraftforge.fml.ModList;
import net.minecraftforge.fml.loading.FMLPaths;

import java.nio.file.Path;

/**
 * Forge implementation of {@link SplashPlatform}, installed by
 * {@link CustomSplash} at mod construction time.
 */
public final class ForgeSplashPlatform implements SplashPlatform {

	private ForgeSplashPlatform() {
	}

	public static void install() {
		SplashPlatform.install(new ForgeSplashPlatform());
	}

	@Override
	public Path getConfigDir() {
		return FMLPaths.CONFIGDIR.get();
	}

	@Override
	public Path getGameDir() {
		return FMLPaths.GAMEDIR.get();
	}

	@Override
	public boolean isModLoaded(String modId) {
		return ModList.get().isLoaded(modId);
	}

	@Override
	public int loadedModCount() {
		return ModList.get().getMods().size();
	}
}
"""

FORGE_INITIALIZER = r"""package dev.arrbrants.customsplash;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod(CustomSplash.MOD_ID)
public class CustomSplash {
	public static final String MOD_ID = "custom-splash";
	public static final Logger LOGGER = LogManager.getLogger(MOD_ID);

	public CustomSplash() {
		ForgeSplashPlatform.install();
		FMLJavaModLoadingContext.get().getModEventBus().addListener(this::onCommonSetup);
		LOGGER.info("Custom Splash has initialized");
	}

	private void onCommonSetup(FMLCommonSetupEvent event) {
		SplashRegistry.reload();
	}
}
"""


def main() -> None:
	versions = FORGE_VERSIONS_FILE.read_text().splitlines()
	fabric_versions = (ROOT / "supported-versions.txt").read_text().splitlines()
	for minecraft in versions:
		if minecraft not in FORGE_SPECS:
			raise SystemExit(f"no Forge spec for {minecraft}")
		if minecraft not in fabric_versions:
			raise SystemExit(f"{minecraft} is not a Fabric version project")

		forge_version, java_version, loader_range, mc_range = FORGE_SPECS[minecraft]
		project = ROOT / "versions" / f"{minecraft}-forge"
		write(project, Path("build.gradle"),
		      BUILD_GRADLE_FG6 if is_fg6(minecraft) else BUILD_GRADLE_FG5)
		write(project, Path("settings.gradle"),
		      (SETTINGS_GRADLE_FG6 if is_fg6(minecraft) else SETTINGS_GRADLE_FG5)
		      .replace("%%MINECRAFT%%", minecraft))
		write(project, Path("gradle.properties"),
		      GRADLE_PROPERTIES
		      .replace("%%MINECRAFT%%", minecraft)
		      .replace("%%FORGE%%", forge_version)
		      .replace("%%JAVA%%", java_version))
		copy_wrapper(project, minecraft)

		for name, content in SOURCES.items():
			write(project, PACKAGE_DIR / name, content)
		write(project, PACKAGE_DIR / "ForgeSplashPlatform.java", FORGE_PLATFORM)
		write(project, PACKAGE_DIR / "CustomSplash.java", FORGE_INITIALIZER)
		write(project, PACKAGE_DIR / "mixin" / "SplashManagerMixin.java", mixin_for(minecraft))

		write(project, RESOURCES_DIR / "META-INF" / "mods.toml",
		      MODS_TOML
		      .replace("%%LOADER_RANGE%%", loader_range)
		      .replace("%%MC_RANGE%%", mc_range))
		write(project, RESOURCES_DIR / "customsplash.mixins.json",
		      MIXINS_JSON.replace("%%COMPAT%%", mixin_compatibility(minecraft)))
		print(f"updated forge {minecraft}")


if __name__ == "__main__":
	main()
