plugins {
	id 'net.neoforged.moddev' version '2.0.+'
	id 'maven-publish'
}

def gitCommit = providers.exec {
	commandLine 'git', 'rev-parse', '--short=8', 'HEAD'
}.standardOutput.asText.getOrElse('').trim()

version = "${rootProject.mod_version}+mc26.1+neoforge" + (gitCommit.isEmpty() ? '' : ".${gitCommit}")
group = rootProject.maven_group
base.archivesName = "custom-splash-${minecraft_version}-neoforge"

neoForge {
	version = "26.1.1.114"

	mods {
		"custom_splash" {
			sourceSet(sourceSets.main)
		}
	}

	runs {
		client {
			client()
			gameDirectory = project.file('run')
			systemProperty 'neoforge.enabledGameTestNamespaces', 'custom-splash'
		}
	}
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_version', minecraft_version
	inputs.property 'neoforge_version', neoforge_version
	filesMatching('META-INF/neoforge.mods.toml') {
		expand version: project.version, minecraft_version: minecraft_version, loader_min_version: loader_min_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = Integer.parseInt(java_version)
}

java {
	withSourcesJar()
}

jar {
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
