modLoader="javafml"
loaderVersion="[48,)"
license="CC0-1.0"

[[mods]]
modId="custom-splash"
version="${version}"
displayName="Custom Splash"
authors="ArrBrants"
description='''A mod that replaces or extends the title screen yellow splash text with custom texts, colours, gradients, placeholders and conditions.'''

[[dependencies.custom-splash]]
modId="forge"
mandatory=true
versionRange="[48,)"
ordering="NONE"
side="BOTH"

[[dependencies.custom-splash]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
